### ISSUE TITLE
GTMNSStringHTMLAdditions

### ISSUE THREAD

**Issue by htyo** [pcjbird/QuickWebKit#2]
GTMNSStringHTMLAdditions 这东西pod 不下来。

**Comment by pcjbird** [comment]
> GTMNSStringHTMLAdditions 这东西pod 不下来。

为啥，是不是你网络有问题？

**Comment by htyo** [comment]
不是的，不信，你自己开个工程pod一下。pod下来只有文件夹，没有类文件

发自我的iPhone

**Comment by pcjbird** [comment]
> 不是的，不信，你自己开个工程pod一下。pod下来只有文件夹，没有类文件 发自我的iPhone
> […](#)
> 在 2020年8月28日，10:12，Mr.P ***@***.***> 写道： ﻿ GTMNSStringHTMLAdditions 这东西pod 不下来。 为啥，是不是你网络有问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
![8881598768303_ pic](https://user-images.githubusercontent.com/6175452/91652647-dae62d00-eacb-11ea-94dc-c0bd07d822af.jpg)
是正常的。
